[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
perfx = "5nY3QahMe7YyWoqbmxeeb71RJoZJjeP3HdV8WBGnder9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "wallet1.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
